(load "main.ss")
(define (test1)
	(eval-one-exp '(define x 0))
	(eval-one-exp '(define y 0))
	(eval-one-exp '(while (< x 12) (set! x (+ x 1)) (if (or (= x 4) (= x 7) (= x 9)) (continue)) (set! y (+ y x))))
	(if (= (eval-one-exp 'y) 58)
		(display "test1 passes: result is 58")
		(display "test2 fails: result is not 58")))

(define (test2)
	(eval-one-exp '(define x 0))
	(eval-one-exp '(define y 0))
	(eval-one-exp '(while (< x 12)
						(set! x (+ x 1))
						(if (or (= x 4) (= x 7) (= x 9))
							(continue))
						(set! z 0)
						(while (<= z x)
							(set! z (+ z 1))
							(if (or (= z 6) (= z 10))
								(continue))
							(set! y (+ y z)))))
	(if (= (eval-one-exp 'y) 282)
		(display "test2 passes: result is 282")
		(display "test2 fails: result is not 282")))

(define (r)
	(test1)
	(display "\n")
	(test2))